title:        512 Tech
tagline:      'A To-The-Point Tech Blog'
description:  'A To-The-Point Tech Blog'
url:          http://512Tech.github.io
version:      1.1.1
author:
  name:       ''
  email:      ''
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
analytics :
  provider : google
  google : 
      tracking_id : 'UA-42875147-5'
